### ISSUE TITLE
Bug create cache directory

### ISSUE THREAD

**Issue by GnaspGames** [GnaspGames/Smelt#87]
A user received this error:

```
Processing /Users/skyrrel/Desktop/smelt/Magic Hard Modules/crafting_altar/ca_craft.mcc

To use the "!event" command you will need to also install the following module into your map: smelt-for-1.11.mcc
Command length: 13,755 (42.32%)

 * The compiled command has been saved to /Users/skyrrel/Desktop/smelt/Magic Hard Modules/crafting_altar/smelt-for-1.11.oc
fs.js:923
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/Users/skyrrel/Desktop/smelt/Magic Hard Modules/crafting_altar/.smelt/cache'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.AddSupportModuleToCache (/usr/local/lib/node_modules/smelt-cli/BangCommands/Helper.js:238:35)
    at /usr/local/lib/node_modules/smelt-cli/Compiler/FileParser.js:40:23
    at Array.forEach (native)
    at FileParser.ProcessFile (/usr/local/lib/node_modules/smelt-cli/Compiler/FileParser.js:34:20)
    at /usr/local/lib/node_modules/smelt-cli/Compiler/StartCompiler.js:42:15
    at Array.forEach (native)
    at Object.ProcessPath (/usr/local/lib/node_modules/smelt-cli/Compiler/StartCompiler.js:39:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/smelt-cli/smelt-compile.js:59:16)
```

It turns out that the `.smelt` directory didn't exist and that the Helper.js code couldn't create the `cache` directory because of it. This was on MacOS, I suspect that it would have worked on Windows.

```
	AddSupportModuleToCache : function(supportModule)
	{
		// Path to the cache file
		var cacheFile = path.resolve(Paths.LocalDirectory + "/.smelt/cache/support-modules.txt");

		// Hash the support module data to add to cache
		var md5sum = crypto.createHash('md5');
		md5sum.update(supportModule.setupData);
		var digest = md5sum.digest('hex');

		// Create the directory if it doesn't exist
		var saveDir = path.dirname(cacheFile);
		if (!fs.existsSync(saveDir)) fs.mkdirSync(saveDir);

		// Add digest to cache file as new line.
		fs.appendFileSync(cacheFile, digest + "\n");
	}
```

The above code in `Helper.js` needs to first check and create the `.smelt` directory.

**Comment by nift4** [comment]
I've fixed this in #103
